baseurl = "https://pellettiero.com/"
languageCode = "en-us"
title = "pellettiero"
# Enable comments by entering your Disqus shortname
disqusShortname = "pellettiero"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = ""
theme = "hugo-hikari-theme"
disableRSS = true
[permalinks]
	post = "/:slug"

[params]
	name = "Michele Pellegrini"
	description = "This blog is actually a blog. Nice!"
	copyright = "powered by [hugo](//gohugo.io) - theme: [hikari](//github.com/digitalcraftsman/hugo-hikari-theme) - ©2017 pellettiero"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "ＥＲＲＯＲ ４０４"
	pageNotFoundSubtitle = "Seems like you got lost...<br>Ｗｉｌｌ ｙｏｕ ｆｉｎｄ ｙｏｕｒｓｅｌｆ <br>ａｇａｉｎ？"

[params.offcanvas]
	# Menu items
	title = "Michele Pellegrini"
	bio = "I am a cheerful, positive and affable person who enjoys all kinds of modern computing."
	followme = "Find me on"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/pellettiero"
